### ISSUE TITLE
Color picker and other tooltip components stays behind when you put the Editor in a Dialog/Modal

### ISSUE THREAD

**Issue by patrickn2** [sjdemartini/mui-tiptap#213] opened 2024-04-18 14:52 UTC
### Describe the bug

If you put the Editor in a Dialog/Modal the color picker will appear behind the dialog/modal popup

### To Reproduce

Just add the Editor in a Dialog or Modal and the color picker tooltip will stay behind the popup

https://codesandbox.io/p/devbox/mui-tiptap-demo-forked-vmndxj

1. Click on Open Dialog
2. Try to change the text Color

### Expected behavior

The tooltips should stay in front of the Dialog

### Screenshots

![image](https://github.com/sjdemartini/mui-tiptap/assets/119355744/dd97571d-2a7b-4b8b-bf4e-7dea309fb046)

### System (please complete the following information)

- mui-tiptap version: [1.8.6]
- tiptap version: [2.3.0]
- Browser: [Chrome]
- Node version: [20.12.0]
- OS: [Windows 11]

I used the Demo

**Comment by sjdemartini** [comment] 2024-04-18 15:58
Duplicate of https://github.com/sjdemartini/mui-tiptap/issues/206. As mentioned there, for what it's worth, the `LinkBubbleMenu` and `TableBubbleMenu` both accept a `container` prop which allow them to work around this issue, though the color picker doesn't currently have the same affordance.

**Closed by sjdemartini** 2024-04-18 15:58 UTC
