### ISSUE TITLE
Choosen color consistency

### ISSUE THREAD

**Issue by Shao-fract** [sjdemartini/mui-tiptap#203] opened 2024-03-31 05:46 UTC
Hi,
Is there a way to prevent the choosen text color to be reseted  to default on pressing return?

I find it pretty non intuitive to have to select again the color on each line change.

**Comment by sjdemartini** [comment] 2024-04-18 16:34
I can't reproduce the issue you are describing. This is using the CodeSandbox linked from the README https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6

![mui-tiptap-color-pressing-return](https://github.com/sjdemartini/mui-tiptap/assets/1647130/72cef0b2-a29c-4b2f-aba9-138169b2b4ff)

Am I misunderstanding what you're doing? If you find that are you still experiencing this, you may want to look at issues for Tiptap itself https://github.com/ueberdosis/tiptap, since the `Color` extension is built into Tiptap and isn't changed by any `mui-tiptap` functionality. Closing this out since not specific to mui-tiptap and can't repro.

**Closed by sjdemartini** 2024-04-18 16:34 UTC

**Comment by Shao-fract** [comment] 2024-04-18 16:41
Ok. I m not experiencing the same behaviour as you. I'll search by myself . Tx anyway
