### ISSUE TITLE
MenuButtonEditLink not displaying edit link pop-up box

### ISSUE THREAD

**Issue by sfkaos** [sjdemartini/mui-tiptap#201] opened 2024-03-21 08:16 UTC
### Describe the bug

The pop-up box for inputting the URL for editing a link does not show up.

### To Reproduce

While using the <MenuButtonEditLink /> control inside of a mui-tiptap editor:

1. Highlight text inside of the editor
2. Click on the edit link button in the menu bar

### Expected behavior
Expectation: A popup box appears allowing user to input URL
Actual: Nothing

### System (please complete the following information):

- mui-tiptap version: 1.8.6
- tiptap version: 2.2.4
- Browser: Chrome
- Node version: 18.17.0
- OS: macOS 14.1.2

**Comment by sjdemartini** [comment] 2024-03-21 17:08
@sfkaos Can you provide more steps to reproduce this? What code are you using, and which extensions are installed and being passed in the `extensions` array? This works in the CodeSandbox linked in the README https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6

My guess is that you may not be including the `LinkBubbleMenuHandler` extension (https://github.com/sjdemartini/mui-tiptap?tab=readme-ov-file#linkbubblemenuhandler) in your `extensions` array for the editor.

**Comment by sfkaos** [comment] 2024-03-22 10:09
Actually ripped the `useExtensions` function directly from the sandbox demo.

I'm not seeing any errors in the dev tools console. I can send a video if that helps.

**Comment by jfily** [comment] 2024-04-05 10:51
You probably didn't add this into the `RichTextEditor` component

```
{() => (
    <>
      <LinkBubbleMenu />
      <TableBubbleMenu />
    </>
  )}
```

**Comment by vitality82** [comment] 2024-04-08 15:26
In my case it's because of rendering the `LinkBubbleMenu` component inside a MUI Dialog, that has a 1300 z-index.
Instead of dealing with z-index values, this worked for me:

`<LinkBubbleMenu container={dialogRef.current} />`

This solution still requires you to control the open/close state via the parent (e.g Parent Dialog closes while edit menu link was open).

**Comment by sjdemartini** [comment] 2024-04-18 16:23
Closing per the last two comments' explanations of fixes. You have to be sure to render `LinkBubbleMenu`, and its `container` prop is the right approach if using the editor within a modal. Please feel free to comment if there is still some remaining issue here.

**Closed by sjdemartini** 2024-04-18 16:23 UTC
